version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html/app
      - ./public:/var/www/html/public
      - ./core:/var/www/html/core
    ports:
      - "8000:80"
    environment:
      - PHP_IDE_CONFIG=serverName=Docker