version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./app:/var/www/html/app
      - ./public:/var/www/html/public
      - ./core:/var/www/html/core
      - ./config.php:/var/www/html/config.php
    ports:
      - "8111:80"
    # environment:
    #   - PHP_IDE_CONFIG=serverName=Docker
    #   - DB_HOST=localhost:3306
    #   - DB_NAME=app
    #   - DB_USERNAME=app
    #   - DB_PASSWORD=app
  #   depends_on:
  #     - mysql
  # mysql:
  #   image: mysql:5.7
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: app
  #     MYSQL_USER: app
  #     MYSQL_PASSWORD: app

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - mysql
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: root
  #   depends_on:
  #     - mysql


